# Generated by Django 4.2.3 on 2023-09-14 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0020_alter_reviews_options'),
        ('users', '0009_rename_is_loggedin_user_isloggedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderOn', models.DateField(default=None, null=True)),
                ('items', models.IntegerField(default=1, null=True)),
                ('price', models.FloatField(default=None, null=True)),
                ('totalPrice', models.FloatField(default=None, null=True)),
                ('productId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('userId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
