# Generated by Django 4.2.3 on 2023-09-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_id_order_orderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='productId',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='userId',
            new_name='user',
        ),
    ]
