# Generated by Django 4.0.6 on 2023-07-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_apple',
            new_name='isApple',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='old_price',
            new_name='oldPrice',
        ),
    ]
