# Generated by Django 4.0.6 on 2023-07-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='mainImage',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_main',
        ),
    ]
