# Generated by Django 4.0.6 on 2023-07-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_image_product_mainimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
