# Generated by Django 4.2.3 on 2023-07-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
    ]
