# Generated by Django 4.2.3 on 2023-07-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_name_category_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
