# Generated by Django 4.0.6 on 2023-07-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_rename_review_reviews_user_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'User review', 'verbose_name_plural': 'User reviews'},
        ),
    ]
