# Generated by Django 4.0.6 on 2023-09-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_reviews_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.FloatField(default=0),
        ),
    ]
