# Generated by Django 4.0.6 on 2023-09-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='review',
            new_name='meanReview',
        ),
    ]
