# Generated by Django 4.0.6 on 2023-10-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meanReview', models.FloatField(blank=True, default=None, null=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Review Line',
                'verbose_name_plural': 'Review Lines',
            },
        ),
    ]
