# Generated by Django 4.2.3 on 2024-03-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_remove_category_is_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_active',
            new_name='isActive',
        ),
    ]
