# Generated by Django 4.2.3 on 2024-03-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_remove_productlogo_product_alter_category_options_and_more'),
        ('products', '0029_rename_is_active_category_isactive'),
    ]

    operations = [
    ]
