# Generated by Django 4.2.3 on 2024-03-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_merge_20240317_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
