# Generated by Django 4.2.3 on 2024-03-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='- Due to the developing, no description is added to products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='leftInStock',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimumAmount',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='oldPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='topUpAmount',
            field=models.IntegerField(default=2),
        ),
    ]
