# Generated by Django 4.0.6 on 2023-07-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_last_name_user_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_loggedin',
            new_name='isLoggedIn',
        ),
    ]
