# Generated by Django 4.0.6 on 2023-09-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_is_loggedin_user_isloggedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isLoggedIn',
            new_name='isOnline',
        ),
    ]
