# Generated by Django 4.2.3 on 2024-03-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_isloggedin_user_isonline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='', max_length=210),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=210),
        ),
    ]
