# Generated by Django 4.0.6 on 2023-09-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0021_alter_product_category'),
        ('orders', '0006_rename_user_order_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('orderLineId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('totalPrice', models.FloatField(default=None)),
                ('orderId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'verbose_name': 'OrderLine',
                'verbose_name_plural': 'OrderLines',
            },
        ),
    ]
