# Generated by Django 4.0.6 on 2023-09-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_category'),
        ('orders', '0006_rename_user_order_userid'),
        ('orderline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='orderId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.CreateModel(
            name='OrderLineProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderline', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orderline.orderline')),
                ('product_text', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'OrderLine product',
                'verbose_name_plural': 'OrderLine products',
            },
        ),
    ]
