# Generated by Django 4.0.6 on 2023-09-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderline', '0002_alter_orderline_orderid_alter_orderline_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='product',
        ),
    ]
