# Generated by Django 4.0.6 on 2023-09-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderline', '0003_remove_orderline_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineproduct',
            old_name='product_text',
            new_name='product',
        ),
    ]
