# Generated by Django 4.2.3 on 2024-01-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderline', '0005_remove_orderline_quantity_orderlineproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
