# Generated by Django 4.2.3 on 2024-01-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderline', '0006_orderline_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
