# Generated by Django 4.2.3 on 2024-01-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderline', '0008_alter_orderline_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineproduct',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
