# Generated by Django 4.2.3 on 2024-01-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderline', '0009_orderlineproduct_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineproduct',
            name='created_at',
        ),
    ]
