# Generated by Django 4.2.3 on 2024-01-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderline', '0010_remove_orderlineproduct_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='created_at',
        ),
        migrations.AddField(
            model_name='orderlineproduct',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
