# Generated by Django 4.2.3 on 2024-01-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderline', '0011_remove_orderline_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
