# Generated by Django 4.2.3 on 2024-03-24 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_orderon'),
        ('orderline', '0012_alter_orderlineproduct_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='orderId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
