# Generated by Django 4.0.6 on 2023-09-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0021_alter_product_category'),
        ('orders', '0005_remove_order_items_remove_order_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('optionId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('totalPrice', models.FloatField(default=None)),
                ('orderId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('productId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
    ]
